version: '3.1'
services:
  openelevation:
    container_name: open-elevation
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - elevnet
    ports:
      - "8080:10000"
    volumes:
      - ./data:/code/data
networks:
  elevnet:
    driver: bridge
